### ISSUE TITLE
Compatiblity

### ISSUE THREAD

**Issue by msd-kharazi** [kitcat2014/KendoUI_Gregorian-Persian-Hijri_Calendar-DatePicker-TimePicker#2]
Hello and thanks for your effort.
I have kendo v2019.3.917 for .net core 3.
Your sample is working properly, However if i just reference just kendo styles of (v2019.3.917) 
[I Mean kendo.common.min.css & kendo.default.min.css]
The sample is not as expected. Please update to the latest version. Thanks in advanced.

**Comment by CyberDepot** [comment]
hi
in feature i want to update kendo ui version
