### ISSUE TITLE
DateTimePicker

### ISSUE THREAD

**Issue by Hamidnch** [kitcat2014/KendoUI_Gregorian-Persian-Hijri_Calendar-DatePicker-TimePicker#4]
سلام وقت شما بخیر.امکانش هست DateTimePicker این نسخه رو هم شمسی بفرمایید.
تشکر

**Comment by CyberDepot** [comment]
سلام، خیلی دوست دارم هم نسخه جدید رو ریلیز کنم و هم DateTimePicker رو شمسی کنم، اما متاسفانه با این شرایط اقتصادی و کاری و فشاری که روی ما هست فعلا نمی تونم، عذر خواهی بنده رو بپذیرید.

**Comment by Mamad4D** [comment]
سلام، وقت بخیر، ضمن تشکر فراوان، با توجه به اینکه نسخه 2018 قدیمی شده و شما هم وقت ندارید این ماژول کاربردی رو بروزرسانی کنید، اگه میشه راهنمایی فرمایید که چطور میتونم تقویم کندو 2021 رو فارسی کنم؟ همونطور که میدونید کندو در ورژن های مختلف ساختارش دچار تغییر میشه. با تشکر

**Comment by CyberDepot** [comment]
سلام دوست من، برای شمسی کردن تقویم کندو شما باید فایل های جاوا اسکریپت مربوطه رو تغییر بدین، نکته مهم تو اینکار این هست که فایلهای های جاوا اسکریپتی که همراه کندو هست به صورت مینیفای شده هستند و در حقیقت برای خوندن کدهای مینیفای شده و تزریق کدهای جدید واقعا کار خیلی سختی رو در پیش دارین، زمان زیادی رو لازم دارین که بتونین اینکارو انجام بدین

**Comment by Mamad4D** [comment]
سلام، ممنون از توضیحات شما، خدا رو شکر موفق شدم تقویم رو برای نسخه 2021 تلریک بروزرسانی کنم
درسته، اصلاح فایل مینیفای واقعا سخته برای همین از سورس بازش که در آدرس https://github.com/telerik/kendo-ui-core هست رو استفاده کردم و مشکل حل شد
همچنین از سورس https://github.com/majid3ma/Kendo-ui-core-shamsi که نسخه 2020 هست استفاده کردم

**Comment by CyberDepot** [comment]
سلام مهندس گرامی، خیلی عالی شده، موفق باشید
